version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - dev_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
      - ./themes/devel:/var/www/html/wp-content/themes/devel-theme
      - ./themes/example-sage:/var/www/html/wp-content/themes/example-sage
      - ./themes/bootstrap5-wordpress-theme:/var/www/html/wp-content/themes/bootstrap5-wordpress-theme
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  behat:
    image: docksal/behat
    volumes:
      - ./behat:/src
    links:
        - hub
        - wordpress
    ports:
        - 8282:80
    environment:
      website: http://wordpress:8000
    entrypoint: "php -S 0.0.0.0:80"
  browser:
    hostname: browser
    # Pick/uncomment one
    # Pin selenium image to an older version
    # See https://github.com/docksal/docksal/issues/1096#issuecomment-543316840
    image: ${SELENIUM_IMAGE:-selenium/standalone-chrome-debug:3.141.59}
    #image: ${SELENIUM_IMAGE:-selenium/standalone-firefox-debug:3.141.59}
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /dev/shm:/dev/shm
    # VNC port for debugging
    # Host: <your-docker-host>:5900 (e.g, localhost:5900, 192.168.64.100:5900)
    # Password: secret
    ports:
      - 5901:5900
  hub:
    image: qualiboo/testing-hub
    ports:
      - 4444:4444
  firefox:
    image: qualiboo/testing-node-firefox
    ports:
      - 5900
    links:
      - hub
      - wordpress
    environment:
      REMOTE_HOST_PARAM: "-maxSession 3 -browser browserName=firefox,maxInstances=3"
  chrome:
    image: qualiboo/testing-node-chrome
    ports:
      - 5900
    links:
      - hub
      - wordpress

volumes:
  dev_db_data: {}
